### ISSUE TITLE
Cannot filter all items at specific patch & items are only shown with current stats

### ISSUE THREAD

**Issue by Endtroducing** [itemization/itemization.info#2]
Hi,

Thanks for making this great site that I just recently discovered. There are two issues / wishes I have for more options:

1. The possibility to check out all items and their stats at a specific patch, e.g. all cloth items for head that are blue and in-game at patch 1.10. Not just those who were added / updated in that specific patch. 

2. When filtering for a specific patch, display the item with the stats at that point, e.g. if I check for slot:legs subtype:cloth added:1.2 I get "Senior Designer's Pantaloons" in the results, but not with the tooltip of the item it was in 1.2 but with the tooltip it was after an upgrade in 1.10. 

Thank you and kind regards.

**Comment by itemization** [comment]
1. It is possible technically but very cumbersome, you would have to do `patch:1.2 patch:1.3 ... patch:1.10` to get that :) it currently works the way you want for classic phases, i.e. if you do `phase:5` it looks at all the items that will exist in phase 5. I will add another operator that does the same for individual patches.
2. This is on purpose because classic is going to use 1.12 stats unfortunately, but items will still be gated by patch/phase.

**Comment by Endtroducing** [comment]
Thank you for the swift and detailed response. That both makes sense.
